USE [fashionDatabase]
GO

--Danh sách Nhân viên Đang làm việc
CREATE OR ALTER VIEW V_NHANVIEN_LAMVIEC
AS
SELECT [MaNV], [HoTen], [SDT], [Email], [TenCV], [TenPB]
FROM NHANVIEN, CHUCVU, PHONGBAN
WHERE	NHANVIEN.TrangThai = 1 AND
		NHANVIEN.MaCV = CHUCVU.MaCV AND
		NHANVIEN.MaPB = PHONGBAN.MaPB
GO

SELECT * FROM V_NHANVIEN_LAMVIEC
GO

--Danh sách Nhân viên Nghỉ việc
CREATE OR ALTER VIEW V_NHANVIEN_NGHIVIEC
AS
SELECT [MaNV], [HoTen], [SDT], [Email], [TenCV], [TenPB]
FROM NHANVIEN, CHUCVU, PHONGBAN
WHERE	NHANVIEN.TrangThai = 0 AND
		NHANVIEN.MaCV = CHUCVU.MaCV AND
		NHANVIEN.MaPB = PHONGBAN.MaPB
GO

SELECT * FROM V_NHANVIEN_NGHIVIEC
GO

--Danh sách Tất cả sản phẩm
CREATE OR ALTER VIEW V_SANPHAM_DANHSACH
AS
SELECT SANPHAM.[MaSP], TenSP, LoaiKichCo, GioiTinh, TenLoaiSP, GiaBan, SoLuong
FROM SANPHAM, KICHCO_SANPHAM, KICHCO, LOAISANPHAM, BIENDONGGIA
WHERE	SANPHAM.MaSP = KICHCO_SANPHAM.MaSP AND KICHCO.MaKC = KICHCO_SANPHAM.MaKC
	AND	SANPHAM.MaSP = BIENDONGGIA.MaSP AND SANPHAM.MaLoaiSP = LOAISANPHAM.MaLoaiSP
GO

SELECT * FROM V_SANPHAM_DANHSACH
GO

--Danh sách các Đơn hàng đã Thanh toán
CREATE OR ALTER VIEW V_DONHANG_THANHTOAN
AS
SELECT DONHANG.[MaDH], NgayDatHang, TongTien, KHACHHANG.HoTen AS HOTEN_KHACH, NHANVIEN.HoTen AS HOTEN_NHANVIEN
FROM DONHANG, KHACHHANG, NHANVIEN
WHERE	DONHANG.MaKH = KHACHHANG.MaKH AND DONHANG.MaNV = NHANVIEN.MaNV
	AND	TrangThaiDH = 1

GO

SELECT * FROM V_DONHANG_THANHTOAN
GO

-- Danh sách Tổng số lần nhập hàng và Tổng tiền Nhập từ Nhà cung cấp
CREATE OR ALTER VIEW V_NHAPHANG_NCC
AS
SELECT [TenNCC], COUNT(MaPNH) AS [TongLanNhap], SUM(TongTien) AS [TongTienNhap]
FROM NHACUNGCAP JOIN PHIEUNHAPHANG ON NHACUNGCAP.MaNCC = PHIEUNHAPHANG.MaNCC
GROUP BY PHIEUNHAPHANG.MaNCC, TenNCC

GO

SELECT * FROM V_NHAPHANG_NCC
GO

-- Danh sách Nhà cung cấp
CREATE OR ALTER VIEW V_NHACUNGCAP_DS
AS
SELECT *
FROM NHACUNGCAP

GO

SELECT * FROM V_NHACUNGCAP_DS
GO

-- Danh sách Nhân viên
CREATE OR ALTER VIEW V_NHANVIEN_DS
AS
SELECT [MaNV], [HoTen], [SDT], [Email], [TenCV], [TenPB]
FROM	NHANVIEN, PHONGBAN, CHUCVU
WHERE	NHANVIEN.MaCV = CHUCVU.MaCV AND
		NHANVIEN.MaPB = PHONGBAN.MaPB
GO

SELECT * FROM V_NHANVIEN_DS
GO

-- Danh sách Khách Hàng
CREATE OR ALTER VIEW V_KHACHHANG_DS
AS
SELECT [MaKH], [HoTen], [SDT], [Email], [DiaChi]
FROM KHACHHANG

GO

SELECT * FROM V_KHACHHANG_DS
GO

-- Danh sách Chi Tiết Đơn hàng
CREATE OR ALTER VIEW V_DONHANG_CHITIET_DS
AS
SELECT DH.[MaDH], [TenSP], [LoaiKichCo], KC.[GioiTinh], CTD.[SoLuong], [GiaTien], KH.HoTen AS HOTEN_KHACH, NV.HoTen AS HOTEN_NHANVIEN
FROM DONHANG DH, CHITIET_DONHANG CTD, KHACHHANG KH, NHANVIEN NV, SANPHAM SP, KICHCO_SANPHAM KCSP, KICHCO KC
WHERE	DH.MaDH = CTD.MaDH AND CTD.MaSP = KCSP.MaSP AND CTD.MaKC = KCSP.MaKC 
	AND KCSP.MaSP = SP.MaSP AND KCSP.MaKC = KC.MaKC AND DH.MaKH = KH.MaKH AND DH.MaNV = NV.MaNV
GO

SELECT * FROM V_DONHANG_CHITIET_DS
GO

-- Danh sách Chi Tiết Phiếu Nhập Hàng
CREATE OR ALTER VIEW V_NHAPHANG_CHITIET_DS
AS
SELECT NH.[MaPNH], [TENSP], [LoaiKichCo], KC.[GioiTinh], [SoLuongNhap], [DonGiaNhap],  [TenNCC], [HoTen]
FROM NHACUNGCAP NCC, PHIEUNHAPHANG NH, CHITIET_PHIEUNHAP CTNH, SANPHAM SP, KICHCO KC, KICHCO_SANPHAM KCSP, NHANVIEN NV
WHERE NCC.MaNCC = NH.MaNCC AND NH.MaPNH = CTNH.MaPNH AND CTNH.MaSP = KCSP.MaSP AND CTNH.MaKC = KCSP.MaKC
	AND NH.MaNV = NV.MaNV AND KCSP.MaKC = KC.MaKC AND KCSP.MaSP = SP.MaSP

GO

SELECT * FROM V_NHAPHANG_CHITIET_DS
GO