USE master
GO
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'shoestoreDB')
BEGIN
	DROP DATABASE shoestoreDB
END

CREATE DATABASE shoestoreDB
GO

USE shoestoreDB
GO


CREATE TABLE USERS
(
  username CHAR(32) NOT NULL,
  password CHAR(16) NOT NULL,
  role CHAR(2) NOT NULL,
  PRIMARY KEY (username)
);

CREATE TABLE CHITIETKHACHHANG
(
  CMND NUMERIC(12,0) NOT NULL,
  DiaChi VARCHAR(100) NOT NULL,
  GioiTinh CHAR(1) NOT NULL,
  SDT NUMERIC(11,0) NOT NULL,
  PRIMARY KEY (CMND)
);

CREATE TABLE PHANLOAIKHACHHANG
(
  MaLoaiKH CHAR(5) NOT NULL,
  TenLoai VARCHAR(20) NOT NULL,
  PRIMARY KEY (MaLoaiKH)
);

CREATE TABLE PHONGBAN
(
  MaPB CHAR(5) NOT NULL,
  TenPB VARCHAR(30) NOT NULL,
  PRIMARY KEY (MaPB)
);

CREATE TABLE CHUCVU
(
  MaCV CHAR(5) NOT NULL,
  TenCV VARCHAR(30) NOT NULL,
  PRIMARY KEY (MaCV)
);

CREATE TABLE CHITIETNHANVIEN
(
  CMND NUMERIC(12,0) NOT NULL,
  DiaChi VARCHAR(100) NOT NULL,
  GioiTinh CHAR(1) NOT NULL,
  SDT NUMERIC(11,0) NOT NULL,
  PRIMARY KEY (CMND)
);

CREATE TABLE LOAISANPHAM
(
  MaLoaiSP CHAR(5) NOT NULL,
  TenLoaiSP VARCHAR(50) NOT NULL,
  PRIMARY KEY (MaLoaiSP)
);

CREATE TABLE CHITIETSANPHAM
(
  MaCTSP CHAR(5) NOT NULL,
  GiaSP INT NOT NULL,
  TinhTrangSP VARCHAR(20) NOT NULL,
  PRIMARY KEY (MaCTSP)
);

CREATE TABLE NHACUNGCAP
(
  MaNCC CHAR(10) NOT NULL,
  TenNCC VARCHAR(20) NOT NULL,
  PRIMARY KEY (MaNCC)
);

CREATE TABLE LOAIHOADON
(
  MaLoaiHD CHAR(10) NOT NULL,
  TenLoaiHD VARCHAR(20) NOT NULL,
  PRIMARY KEY (MaLoaiHD)
);

CREATE TABLE PHIEUXUAT
(
  MaPX CHAR(10) NOT NULL,
  NgayXuat DATE NOT NULL,
  LyDo VARCHAR(100) NOT NULL,
  PRIMARY KEY (MaPX)
);

CREATE TABLE KHACHHANG
(
  MaKH CHAR(10) NOT NULL,
  HoKH VARCHAR(10) NOT NULL,
  HoLotKH VARCHAR(30) NOT NULL,
  TenKH VARCHAR(10) NOT NULL,
  username CHAR(32) NOT NULL,
  MaLoaiKH CHAR(5) NOT NULL,
  CMND NUMERIC(12,0) NOT NULL,
  PRIMARY KEY (MaKH),
  FOREIGN KEY (username) REFERENCES USERS(username),
  FOREIGN KEY (MaLoaiKH) REFERENCES PHANLOAIKHACHHANG(MaLoaiKH),
  FOREIGN KEY (CMND) REFERENCES CHITIETKHACHHANG(CMND)
);

CREATE TABLE NHANVIEN
(
  MaNV CHAR(5) NOT NULL,
  HoNV VARCHAR(10) NOT NULL,
  HoLotNV VARCHAR(30) NOT NULL,
  TenNV VARCHAR(10) NOT NULL,
  MaCV CHAR(5) NOT NULL,
  MaPB CHAR(5) NOT NULL,
  CMND NUMERIC(12,0) NOT NULL,
  PRIMARY KEY (MaNV),
  FOREIGN KEY (MaCV) REFERENCES CHUCVU(MaCV),
  FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB),
  FOREIGN KEY (CMND) REFERENCES CHITIETNHANVIEN(CMND)
);

CREATE TABLE SANPHAM
(
  MaSP CHAR(10) NOT NULL,
  TenSP VARCHAR(50) NOT NULL,
  MaLoaiSP CHAR(5) NOT NULL,
  MaCTSP CHAR(5) NOT NULL,
  MaNCC CHAR(10) NOT NULL,
  PRIMARY KEY (MaSP),
  FOREIGN KEY (MaLoaiSP) REFERENCES LOAISANPHAM(MaLoaiSP),
  FOREIGN KEY (MaCTSP) REFERENCES CHITIETSANPHAM(MaCTSP),
  FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE MATHANG_NCC
(
  MaSP CHAR(10) NOT NULL,
  MaNCC CHAR(10) NOT NULL,
  SoLuong INT NOT NULL,
  MaSP CHAR(10) NOT NULL,
  MaNCC CHAR(10) NOT NULL,
  PRIMARY KEY (MaSP, MaNCC),
  FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
  FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

CREATE TABLE DONHANG
(
  MaDH CHAR(10) NOT NULL,
  NgayDatHang DATE NOT NULL,
  NgayGiaoHang DATE NOT NULL,
  PTThanhToan VARCHAR(20) NOT NULL,
  TongTien INT NOT NULL,
  MaKH CHAR(10) NOT NULL,
  MaNV CHAR(5) NOT NULL,
  PRIMARY KEY (MaDH),
  FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
  FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE CTDONHANG
(
  MaDH CHAR(10) NOT NULL,
  MaSP CHAR(10) NOT NULL,
  SoLuongDat INT NOT NULL,
  DonGia INT NOT NULL,
  MaDH CHAR(10) NOT NULL,
  MaSP CHAR(10) NOT NULL,
  PRIMARY KEY (MaDH, MaSP),
  FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH),
  FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE HOADON
(
  MaHD CHAR(10) NOT NULL,
  NgayLap DATE NOT NULL,
  TongTien INT NOT NULL,
  MaKH CHAR(10) NOT NULL,
  MaDH CHAR(10) NOT NULL,
  MaNV CHAR(5) NOT NULL,
  MaLoaiHD CHAR(10) NOT NULL,
  PRIMARY KEY (MaHD),
  FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
  FOREIGN KEY (MaDH) REFERENCES DONHANG(MaDH),
  FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
  FOREIGN KEY (MaLoaiHD) REFERENCES LOAIHOADON(MaLoaiHD)
);

CREATE TABLE TONKHO
(
  MaSP CHAR(10) NOT NULL,
  Thang FLOAT NOT NULL,
  Nam FLOAT NOT NULL,
  TonDK FLOAT NOT NULL,
  TonCK FLOAT NOT NULL,
  NhapTK FLOAT NOT NULL,
  XuatTK FLOAT NOT NULL,
  MaSP CHAR(10) NOT NULL,
  PRIMARY KEY (MaSP, Thang, Nam),
  FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE CTPHIEUXUAT
(
  MaPX CHAR(10) NOT NULL,
  MaSP CHAR(10) NOT NULL,
  SoLuongXuat FLOAT NOT NULL,
  DonGiaXuat INT NOT NULL,
  MaPX CHAR(10) NOT NULL,
  MaSP CHAR(10) NOT NULL,
  PRIMARY KEY (MaPX, MaSP),
  FOREIGN KEY (MaPX) REFERENCES PHIEUXUAT(MaPX),
  FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);