//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENDONGGIA
    {
        public string MaSP { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public decimal GiaBan { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
