//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DONHANG
    {
        public string MaDH { get; set; }
        public string MaSP { get; set; }
        public string MaKC { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaTien { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual KICHCO_SANPHAM KICHCO_SANPHAM { get; set; }
    }
}
