//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KICHCO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KICHCO()
        {
            this.KICHCO_SANPHAM = new HashSet<KICHCO_SANPHAM>();
        }
    
        public string MaKC { get; set; }
        public double LoaiKichCo { get; set; }
        public string GioiTinh { get; set; }
        public double ChieuDai { get; set; }
        public double ChieuRong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KICHCO_SANPHAM> KICHCO_SANPHAM { get; set; }
    }
}
