//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fashionDatabaseEntities : DbContext
    {
        public fashionDatabaseEntities()
            : base("name=fashionDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIENDONGGIA> BIENDONGGIAs { get; set; }
        public virtual DbSet<CHITIET_DONHANG> CHITIET_DONHANG { get; set; }
        public virtual DbSet<CHITIET_PHIEUNHAP> CHITIET_PHIEUNHAP { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DONHANG> DONHANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KICHCO> KICHCOes { get; set; }
        public virtual DbSet<KICHCO_SANPHAM> KICHCO_SANPHAM { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUNHAPHANG> PHIEUNHAPHANGs { get; set; }
        public virtual DbSet<PHONGBAN> PHONGBANs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<V_DONHANG_CHITIET_DS> V_DONHANG_CHITIET_DS { get; set; }
        public virtual DbSet<V_DONHANG_THANHTOAN> V_DONHANG_THANHTOAN { get; set; }
        public virtual DbSet<V_KHACHHANG_DS> V_KHACHHANG_DS { get; set; }
        public virtual DbSet<V_NHACUNGCAP_DS> V_NHACUNGCAP_DS { get; set; }
        public virtual DbSet<V_NHANVIEN_DS> V_NHANVIEN_DS { get; set; }
        public virtual DbSet<V_NHANVIEN_LAMVIEC> V_NHANVIEN_LAMVIEC { get; set; }
        public virtual DbSet<V_NHANVIEN_NGHIVIEC> V_NHANVIEN_NGHIVIEC { get; set; }
        public virtual DbSet<V_NHAPHANG_CHITIET_DS> V_NHAPHANG_CHITIET_DS { get; set; }
        public virtual DbSet<V_SANPHAM_DANHSACH> V_SANPHAM_DANHSACH { get; set; }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_ChucVu")]
        public virtual IQueryable<fn_TimKiem_ChucVu_Result> fn_TimKiem_ChucVu(string tencv)
        {
            var tencvParameter = tencv != null ?
                new ObjectParameter("tencv", tencv) :
                new ObjectParameter("tencv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_ChucVu_Result>("[fashionDatabaseEntities].[fn_TimKiem_ChucVu](@tencv)", tencvParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_DONHANG")]
        public virtual IQueryable<fn_TimKiem_DONHANG_Result> fn_TimKiem_DONHANG(string madh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_DONHANG_Result>("[fashionDatabaseEntities].[fn_TimKiem_DONHANG](@madh)", madhParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_KHACHHANG")]
        public virtual IQueryable<fn_TimKiem_KHACHHANG_Result> fn_TimKiem_KHACHHANG(string tenkh)
        {
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_KHACHHANG_Result>("[fashionDatabaseEntities].[fn_TimKiem_KHACHHANG](@tenkh)", tenkhParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_LoaiSanPham")]
        public virtual IQueryable<fn_TimKiem_LoaiSanPham_Result> fn_TimKiem_LoaiSanPham(string tenloaisp)
        {
            var tenloaispParameter = tenloaisp != null ?
                new ObjectParameter("tenloaisp", tenloaisp) :
                new ObjectParameter("tenloaisp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_LoaiSanPham_Result>("[fashionDatabaseEntities].[fn_TimKiem_LoaiSanPham](@tenloaisp)", tenloaispParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_NhaCungCap")]
        public virtual IQueryable<fn_TimKiem_NhaCungCap_Result> fn_TimKiem_NhaCungCap(string tenncc)
        {
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_NhaCungCap_Result>("[fashionDatabaseEntities].[fn_TimKiem_NhaCungCap](@tenncc)", tennccParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_NhanVien_TheoTen")]
        public virtual IQueryable<fn_TimKiem_NhanVien_TheoTen_Result> fn_TimKiem_NhanVien_TheoTen(string tennv)
        {
            var tennvParameter = tennv != null ?
                new ObjectParameter("tennv", tennv) :
                new ObjectParameter("tennv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_NhanVien_TheoTen_Result>("[fashionDatabaseEntities].[fn_TimKiem_NhanVien_TheoTen](@tennv)", tennvParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_PhieuMuaHang")]
        public virtual IQueryable<fn_TimKiem_PhieuMuaHang_Result> fn_TimKiem_PhieuMuaHang(string mapmh)
        {
            var mapmhParameter = mapmh != null ?
                new ObjectParameter("mapmh", mapmh) :
                new ObjectParameter("mapmh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_PhieuMuaHang_Result>("[fashionDatabaseEntities].[fn_TimKiem_PhieuMuaHang](@mapmh)", mapmhParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_SanPham")]
        public virtual IQueryable<fn_TimKiem_SanPham_Result> fn_TimKiem_SanPham(string tensp)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_SanPham_Result>("[fashionDatabaseEntities].[fn_TimKiem_SanPham](@tensp)", tenspParameter);
        }
    
        [DbFunction("fashionDatabaseEntities", "fn_TimKiem_TenPhongBan")]
        public virtual IQueryable<fn_TimKiem_TenPhongBan_Result> fn_TimKiem_TenPhongBan(string tenpb)
        {
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiem_TenPhongBan_Result>("[fashionDatabaseEntities].[fn_TimKiem_TenPhongBan](@tenpb)", tenpbParameter);
        }
    
        public virtual int sp_CapNhatChucVu(string macv, string tencv)
        {
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            var tencvParameter = tencv != null ?
                new ObjectParameter("tencv", tencv) :
                new ObjectParameter("tencv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatChucVu", macvParameter, tencvParameter);
        }
    
        public virtual int sp_CapNhatNhaCungCap(string mancc, string tenncc)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatNhaCungCap", manccParameter, tennccParameter);
        }
    
        public virtual int sp_CapNhatNhanVien(string manv, string hoten, string sdt, string email, Nullable<System.DateTime> ngaysinh, string gioitinh, string diachi, string username, string userpASs, Nullable<int> tinhtrang, string macv, string mapb)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var userpASsParameter = userpASs != null ?
                new ObjectParameter("userpASs", userpASs) :
                new ObjectParameter("userpASs", typeof(string));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatNhanVien", manvParameter, hotenParameter, sdtParameter, emailParameter, ngaysinhParameter, gioitinhParameter, diachiParameter, usernameParameter, userpASsParameter, tinhtrangParameter, macvParameter, mapbParameter);
        }
    
        public virtual int sp_CapNhatPhieuNhapHang(string mapmh, Nullable<System.DateTime> ngaynhap, Nullable<decimal> tongtien, string manv, string mancc)
        {
            var mapmhParameter = mapmh != null ?
                new ObjectParameter("mapmh", mapmh) :
                new ObjectParameter("mapmh", typeof(string));
    
            var ngaynhapParameter = ngaynhap.HasValue ?
                new ObjectParameter("ngaynhap", ngaynhap) :
                new ObjectParameter("ngaynhap", typeof(System.DateTime));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("tongtien", tongtien) :
                new ObjectParameter("tongtien", typeof(decimal));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatPhieuNhapHang", mapmhParameter, ngaynhapParameter, tongtienParameter, manvParameter, manccParameter);
        }
    
        public virtual int sp_CapNhatPhongBan(string mapb, string tenpb)
        {
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatPhongBan", mapbParameter, tenpbParameter);
        }
    
        public virtual int sp_CapNhatSanPham(string mASp, string tensp, Nullable<decimal> giASp, string maloaisp, string mausac, string chatlieu, string doituong)
        {
            var mASpParameter = mASp != null ?
                new ObjectParameter("mASp", mASp) :
                new ObjectParameter("mASp", typeof(string));
    
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var giASpParameter = giASp.HasValue ?
                new ObjectParameter("giASp", giASp) :
                new ObjectParameter("giASp", typeof(decimal));
    
            var maloaispParameter = maloaisp != null ?
                new ObjectParameter("maloaisp", maloaisp) :
                new ObjectParameter("maloaisp", typeof(string));
    
            var mausacParameter = mausac != null ?
                new ObjectParameter("mausac", mausac) :
                new ObjectParameter("mausac", typeof(string));
    
            var chatlieuParameter = chatlieu != null ?
                new ObjectParameter("chatlieu", chatlieu) :
                new ObjectParameter("chatlieu", typeof(string));
    
            var doituongParameter = doituong != null ?
                new ObjectParameter("doituong", doituong) :
                new ObjectParameter("doituong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatSanPham", mASpParameter, tenspParameter, giASpParameter, maloaispParameter, mausacParameter, chatlieuParameter, doituongParameter);
        }
    
        public virtual int sp_MuaHang(string madh, string mASp, Nullable<int> soluong, Nullable<double> size, string gioitinh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var mASpParameter = mASp != null ?
                new ObjectParameter("mASp", mASp) :
                new ObjectParameter("mASp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(double));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MuaHang", madhParameter, mASpParameter, soluongParameter, sizeParameter, gioitinhParameter);
        }
    
        public virtual int sp_NhapHang(string mapnh, string mASp, Nullable<int> soluong, Nullable<double> size, string gioitinh, Nullable<int> tinhtrang)
        {
            var mapnhParameter = mapnh != null ?
                new ObjectParameter("mapnh", mapnh) :
                new ObjectParameter("mapnh", typeof(string));
    
            var mASpParameter = mASp != null ?
                new ObjectParameter("mASp", mASp) :
                new ObjectParameter("mASp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(double));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NhapHang", mapnhParameter, mASpParameter, soluongParameter, sizeParameter, gioitinhParameter, tinhtrangParameter);
        }
    
        public virtual int sp_TaoDonHang(string makh, string manv)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoDonHang", makhParameter, manvParameter);
        }
    
        public virtual int sp_ThemChucVu(string macv, string tencv)
        {
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            var tencvParameter = tencv != null ?
                new ObjectParameter("tencv", tencv) :
                new ObjectParameter("tencv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChucVu", macvParameter, tencvParameter);
        }
    
        public virtual int sp_ThemKhachHang(string hoten, string sdt, string diachi, string email, Nullable<System.DateTime> ngaysinh, string gioitinh)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemKhachHang", hotenParameter, sdtParameter, diachiParameter, emailParameter, ngaysinhParameter, gioitinhParameter);
        }
    
        public virtual int sp_ThemLoaiSP(string tenloaisp)
        {
            var tenloaispParameter = tenloaisp != null ?
                new ObjectParameter("tenloaisp", tenloaisp) :
                new ObjectParameter("tenloaisp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLoaiSP", tenloaispParameter);
        }
    
        public virtual int sp_ThemNhaCungCap(string mancc, string tenncc)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhaCungCap", manccParameter, tennccParameter);
        }
    
        public virtual int sp_ThemNhanVien(string manv, string hoten, string sdt, string email, Nullable<System.DateTime> ngaysinh, string gioitinh, string diachi, string username, string userpASs, Nullable<int> tinhtrang, string macv, string mapb)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var ngaysinhParameter = ngaysinh.HasValue ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(System.DateTime));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var userpASsParameter = userpASs != null ?
                new ObjectParameter("userpASs", userpASs) :
                new ObjectParameter("userpASs", typeof(string));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", manvParameter, hotenParameter, sdtParameter, emailParameter, ngaysinhParameter, gioitinhParameter, diachiParameter, usernameParameter, userpASsParameter, tinhtrangParameter, macvParameter, mapbParameter);
        }
    
        public virtual int sp_ThemPhieuNhapHang(Nullable<System.DateTime> ngaynhap, string manv, string mancc)
        {
            var ngaynhapParameter = ngaynhap.HasValue ?
                new ObjectParameter("ngaynhap", ngaynhap) :
                new ObjectParameter("ngaynhap", typeof(System.DateTime));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhieuNhapHang", ngaynhapParameter, manvParameter, manccParameter);
        }
    
        public virtual int sp_ThemPhongBan(string mapb, string tenpb)
        {
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemPhongBan", mapbParameter, tenpbParameter);
        }
    
        public virtual int sp_ThemSanPham(string tensp, Nullable<decimal> giASp, string maloaisp, string mausac, string chatlieu, string doituong, Nullable<int> tinhtrang)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            var giASpParameter = giASp.HasValue ?
                new ObjectParameter("giASp", giASp) :
                new ObjectParameter("giASp", typeof(decimal));
    
            var maloaispParameter = maloaisp != null ?
                new ObjectParameter("maloaisp", maloaisp) :
                new ObjectParameter("maloaisp", typeof(string));
    
            var mausacParameter = mausac != null ?
                new ObjectParameter("mausac", mausac) :
                new ObjectParameter("mausac", typeof(string));
    
            var chatlieuParameter = chatlieu != null ?
                new ObjectParameter("chatlieu", chatlieu) :
                new ObjectParameter("chatlieu", typeof(string));
    
            var doituongParameter = doituong != null ?
                new ObjectParameter("doituong", doituong) :
                new ObjectParameter("doituong", typeof(string));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", tenspParameter, giASpParameter, maloaispParameter, mausacParameter, chatlieuParameter, doituongParameter, tinhtrangParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_ChucVu_Result> sp_TimKiem_ChucVu(string tencv)
        {
            var tencvParameter = tencv != null ?
                new ObjectParameter("tencv", tencv) :
                new ObjectParameter("tencv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_ChucVu_Result>("sp_TimKiem_ChucVu", tencvParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_DONHANG_Result> sp_TimKiem_DONHANG(string madh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_DONHANG_Result>("sp_TimKiem_DONHANG", madhParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_KhachHang_Result> sp_TimKiem_KhachHang(string tenkh)
        {
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("tenkh", tenkh) :
                new ObjectParameter("tenkh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_KhachHang_Result>("sp_TimKiem_KhachHang", tenkhParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_LoaiSanPham_Result> sp_TimKiem_LoaiSanPham(string tenloaisp)
        {
            var tenloaispParameter = tenloaisp != null ?
                new ObjectParameter("tenloaisp", tenloaisp) :
                new ObjectParameter("tenloaisp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_LoaiSanPham_Result>("sp_TimKiem_LoaiSanPham", tenloaispParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_NhaCungCap_Result> sp_TimKiem_NhaCungCap(string tenncc)
        {
            var tennccParameter = tenncc != null ?
                new ObjectParameter("tenncc", tenncc) :
                new ObjectParameter("tenncc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_NhaCungCap_Result>("sp_TimKiem_NhaCungCap", tennccParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_NhanVien_TheoTen_Result> sp_TimKiem_NhanVien_TheoTen(string tennv)
        {
            var tennvParameter = tennv != null ?
                new ObjectParameter("tennv", tennv) :
                new ObjectParameter("tennv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_NhanVien_TheoTen_Result>("sp_TimKiem_NhanVien_TheoTen", tennvParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_NhanVien_Thuoc_PhongBan_Result> sp_TimKiem_NhanVien_Thuoc_PhongBan(string tenpb)
        {
            var tenpbParameter = tenpb != null ?
                new ObjectParameter("tenpb", tenpb) :
                new ObjectParameter("tenpb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_NhanVien_Thuoc_PhongBan_Result>("sp_TimKiem_NhanVien_Thuoc_PhongBan", tenpbParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_PhieuMuaHang_Result> sp_TimKiem_PhieuMuaHang(string mapmh)
        {
            var mapmhParameter = mapmh != null ?
                new ObjectParameter("mapmh", mapmh) :
                new ObjectParameter("mapmh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_PhieuMuaHang_Result>("sp_TimKiem_PhieuMuaHang", mapmhParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_SanPham_Result> sp_TimKiem_SanPham(string tensp)
        {
            var tenspParameter = tensp != null ?
                new ObjectParameter("tensp", tensp) :
                new ObjectParameter("tensp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_SanPham_Result>("sp_TimKiem_SanPham", tenspParameter);
        }
    
        public virtual ObjectResult<sp_Tinh_TongTien_DonHang_Result> sp_Tinh_TongTien_DonHang(string madh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tinh_TongTien_DonHang_Result>("sp_Tinh_TongTien_DonHang", madhParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TinhTongDoanhThuTheoThang(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TinhTongDoanhThuTheoThang", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Tong_NhanVien_DangLamViec()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Tong_NhanVien_DangLamViec");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Tong_NhanVien_NghiViec()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Tong_NhanVien_NghiViec");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Tong_SanPham_DangKinhDoanh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Tong_SanPham_DangKinhDoanh");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Tong_SanPham_NgungKinhDoanh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Tong_SanPham_NgungKinhDoanh");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Tong_SoLan_MuaHang(string mancc)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Tong_SoLan_MuaHang", manccParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Tong_SoLuong_SanPham_DaMua(string mancc)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Tong_SoLuong_SanPham_DaMua", manccParameter);
        }
    
        public virtual int sp_UPDATECTDONHANG_SoLuong(string madh, string mASp, Nullable<int> soluong, Nullable<double> size, string gioitinh)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var mASpParameter = mASp != null ?
                new ObjectParameter("mASp", mASp) :
                new ObjectParameter("mASp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(double));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATECTDONHANG_SoLuong", madhParameter, mASpParameter, soluongParameter, sizeParameter, gioitinhParameter);
        }
    
        public virtual int sp_UPDATECTPhieuNhap_SoLuong(string mapnh, string mASp, Nullable<int> soluong, Nullable<double> size, string gioitinh, Nullable<int> tinhtrang)
        {
            var mapnhParameter = mapnh != null ?
                new ObjectParameter("mapnh", mapnh) :
                new ObjectParameter("mapnh", typeof(string));
    
            var mASpParameter = mASp != null ?
                new ObjectParameter("mASp", mASp) :
                new ObjectParameter("mASp", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(double));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATECTPhieuNhap_SoLuong", mapnhParameter, mASpParameter, soluongParameter, sizeParameter, gioitinhParameter, tinhtrangParameter);
        }
    
        public virtual int sp_UPDATEDonHang(string madh, Nullable<int> trangthai)
        {
            var madhParameter = madh != null ?
                new ObjectParameter("madh", madh) :
                new ObjectParameter("madh", typeof(string));
    
            var trangthaiParameter = trangthai.HasValue ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATEDonHang", madhParameter, trangthaiParameter);
        }
    
        public virtual int sp_UPDATEKhachHang(string maKH, string hoTen, string sDT, string email, string ngaysinh, string gioitinh, string diaChi)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var ngaysinhParameter = ngaysinh != null ?
                new ObjectParameter("ngaysinh", ngaysinh) :
                new ObjectParameter("ngaysinh", typeof(string));
    
            var gioitinhParameter = gioitinh != null ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATEKhachHang", maKHParameter, hoTenParameter, sDTParameter, emailParameter, ngaysinhParameter, gioitinhParameter, diaChiParameter);
        }
    
        public virtual int sp_UPDATELoaiSP(string maLoaiSP, string tenLoaiSP)
        {
            var maLoaiSPParameter = maLoaiSP != null ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(string));
    
            var tenLoaiSPParameter = tenLoaiSP != null ?
                new ObjectParameter("TenLoaiSP", tenLoaiSP) :
                new ObjectParameter("TenLoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UPDATELoaiSP", maLoaiSPParameter, tenLoaiSPParameter);
        }
    
        public virtual int sp_XoaChucVu(string macv)
        {
            var macvParameter = macv != null ?
                new ObjectParameter("macv", macv) :
                new ObjectParameter("macv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChucVu", macvParameter);
        }
    
        public virtual int sp_xoaCTDONHANG(string mact, string mASp, string makc)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var mASpParameter = mASp != null ?
                new ObjectParameter("mASp", mASp) :
                new ObjectParameter("mASp", typeof(string));
    
            var makcParameter = makc != null ?
                new ObjectParameter("makc", makc) :
                new ObjectParameter("makc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_xoaCTDONHANG", mactParameter, mASpParameter, makcParameter);
        }
    
        public virtual int sp_XoaKhachHang(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaKhachHang", maKHParameter);
        }
    
        public virtual int sp_XoaNhaCungCap(string mancc)
        {
            var manccParameter = mancc != null ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhaCungCap", manccParameter);
        }
    
        public virtual int sp_XoaNhanVien(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVien", manvParameter);
        }
    
        public virtual int sp_XoaPhieuNhapHang(string mapmh)
        {
            var mapmhParameter = mapmh != null ?
                new ObjectParameter("mapmh", mapmh) :
                new ObjectParameter("mapmh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPhieuNhapHang", mapmhParameter);
        }
    
        public virtual int sp_XoaPhongBan(string mapb)
        {
            var mapbParameter = mapb != null ?
                new ObjectParameter("mapb", mapb) :
                new ObjectParameter("mapb", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaPhongBan", mapbParameter);
        }
    
        public virtual int sp_XoASanPham(string mASp)
        {
            var mASpParameter = mASp != null ?
                new ObjectParameter("mASp", mASp) :
                new ObjectParameter("mASp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoASanPham", mASpParameter);
        }
    }
}
