//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SANPHAM_DANHSACH
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public double LoaiKichCo { get; set; }
        public string GioiTinh { get; set; }
        public string TenLoaiSP { get; set; }
        public decimal GiaBan { get; set; }
        public int SoLuong { get; set; }
    }
}
