//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CSDL_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.BIENDONGGIAs = new HashSet<BIENDONGGIA>();
            this.KICHCO_SANPHAM = new HashSet<KICHCO_SANPHAM>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public string MauSac { get; set; }
        public string ChatLieu { get; set; }
        public string MaLoaiSP { get; set; }
        public string DoiTuong { get; set; }
        public string HinhAnh { get; set; }
        public int TinhTrangSP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENDONGGIA> BIENDONGGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KICHCO_SANPHAM> KICHCO_SANPHAM { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
