//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CSDL_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DONHANG_CHITIET_DS
    {
        public string MaDH { get; set; }
        public string TenSP { get; set; }
        public double LoaiKichCo { get; set; }
        public string GioiTinh { get; set; }
        public int SoLuong { get; set; }
        public decimal GiaTien { get; set; }
        public string HOTEN_KHACH { get; set; }
        public string HOTEN_NHANVIEN { get; set; }
    }
}
