//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CSDL_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DONHANG_THANHTOAN
    {
        public string MaDH { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public decimal TongTien { get; set; }
        public string HOTEN_KHACH { get; set; }
        public string HOTEN_NHANVIEN { get; set; }
    }
}
