//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CSDL_DEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_NHAPHANG_CHITIET_DS
    {
        public string MaPNH { get; set; }
        public string TENSP { get; set; }
        public double LoaiKichCo { get; set; }
        public string GioiTinh { get; set; }
        public int SoLuongNhap { get; set; }
        public decimal DonGiaNhap { get; set; }
        public string TenNCC { get; set; }
        public string HoTen { get; set; }
    }
}
